apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "energy-reading.labels" . | nindent 4 }}
    {{- include "frontend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend  # Fixed name
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PRODUCER_URL
              value: {{ .Values.frontend.env.producerUrl | quote }}
            - name: CONSUMER_URL
              value: {{ .Values.frontend.env.consumerUrl | quote }}
            - name: ENVIRONMENT
              value: "production" # Added for your Python logic
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}