services:
  redis-service:
    image: docker.io/library/redis:7-alpine
    container_name: redis-service
    networks:
      - energy-reading-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: services/producer/Dockerfile
    image: localhost/energy_reading/producer:latest
    container_name: producer
    environment:
      - REDIS_HOST=redis-service # Docker DNS resolves this to the redis container IP
      - REDIS_PORT=6379
    networks:
      - energy-reading-net
    depends_on:
      redis-service:
        condition: service_healthy

  consumer:
    build:
      context: .
      dockerfile: services/consumer/Dockerfile
    image: localhost/energy_reading/consumer:latest
    container_name: consumer
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - STREAM_NAME=energy_readings
      - CONSUMER_GROUP=processing_group
    networks:
      - energy-reading-net
    depends_on:
      redis-service:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: services/frontend/Dockerfile
    image: localhost/energy_reading/frontend:latest
    container_name: frontend
    ports:
      - "8080:8080" # This is the "bridge" from your laptop to the container
    environment:
      - PRODUCER_URL=http://producer:8000
      - CONSUMER_URL=http://consumer:8000
      - ENVIRONMENT=development
    networks:
      - energy-reading-net
    depends_on:
      producer:
        condition: service_started
      consumer:
        condition: service_started

networks:
  energy-reading-net:
    driver: bridge
