services:
  redis-service:
    image: docker.io/library/redis:7-alpine
    container_name: redis-service
    networks:
      - energy-reading-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: services/producer/Dockerfile
    image: localhost/energy_reading/producer:latest
    container_name: producer
    environment:
      - REDIS_HOST=redis-service # Docker DNS resolves this to the redis container IP
      - REDIS_PORT=6379
    ports:
      - "8080:8000" # Host:Container
    networks:
      - energy-reading-net
    depends_on:
      redis-service:
        condition: service_healthy

  consumer:
    build:
      context: .
      dockerfile: services/consumer/Dockerfile
    image: localhost/energy_reading/consumer:latest
    container_name: consumer
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - STREAM_NAME=energy_readings
      - CONSUMER_GROUP=processing_group
    ports:
      - "8081:8000" # Host:Container
    networks:
      - energy-reading-net
    depends_on:
      redis-service:
        condition: service_healthy

networks:
  energy-reading-net:
    driver: bridge
