[project]
name = "frontend"
version = "0.1.0"
description = "frontend gui"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "nicegui>=3.7.1",
    "shared_lib",
]
