[project]
name = "producer"
version = "0.1.0"
description = "sends energy data to redis service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "shared_lib",
    "fastapi>=0.128.8",
    "redis>=7.1.1",
]
